version: '3'
services:
  postgres:
    container_name: js-date-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '6412:5432'
  postgres-test:
    container_name: js-date-postgres-test
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '6413:5432'